[[module.imports]]
path = "github.com/razonyang/hb-giscus"

[[module.imports]]
path = "github.com/razonyang/hb-docs"

[params.hugopress.modules.hb-docs-comments-giscus.hooks.hb-docs-doc-comments]

[params.hugopress.modules.hb-docs-comments-giscus.hooks.body-end]
